name: Deploy TODO List
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Install
        run: npm ci
        working-directory: ./react-todo-list-app
      - name: Build app
        run: npm run build
        working-directory: ./react-todo-list-app
      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action : Automatically deploy your project to GitHub Pages with GitHub Actions.
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: react-todo-list-app/build
